style_edition = "2024"

# Stable

max_width = 88
newline_style = "Native"
use_field_init_shorthand = true
use_try_shorthand = true

# Unstable

normalize_comments = true
normalize_doc_attributes = true
imports_granularity = "Module"
group_imports = "StdExternalCrate"
format_macro_matchers = true
