[package]
name = "valust"
keywords = ["validator", "data"]
description = "A data validation library for Rust"

version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
categories.workspace = true

[dependencies]
valust-derive = { workspace = true, optional = true }

[features]
default = ["derive"]
derive = ["valust-derive"]

[lints]
workspace = true
