[package]
name = "valust"
version = "0.1.0"
edition = "2021"
readme = "../README.md"

[dependencies]
valust-derive = { workspace = true, optional = true }

[features]
default = ["derive"]
derive = ["valust-derive"]
